// id	                    snowflake	                            id of the message
// channel_id	            snowflake	                            id of the channel the message was sent in
// guild_id?	            snowflake	                            id of the guild the message was sent in
// author*	                user object	                            the author of this message (not guaranteed to be a valid user, see below)
// member?**	            partial guild member object	            member properties for this message's author
// content	                string	                                contents of the message
// timestamp	            ISO8601 timestamp	                    when this message was sent
// edited_timestamp	        ?ISO8601 timestamp	                    when this message was edited (or null if never)
// tts	                    boolean	                                whether this was a TTS message
// mention_everyone	        boolean	                                whether this message mentions everyone
// mentions***	            array of user                           objects, with an additional partial member field	users specifically mentioned in the message
// mention_roles	        array of role object ids	            roles specifically mentioned in this message
// mention_channels?****	array of channel mention objects	    channels specifically mentioned in this message
// attachments	            array of attachment objects	            any attached files
// embeds	                array of embed objects	                any embedded content
// reactions?	            array of reaction objects	            reactions to the message
// nonce?	                integer or string	                    used for validating a message was sent
// pinned	                boolean	                                whether this message is pinned
// webhook_id?	            snowflake	                            if the message is generated by a webhook, this is the webhook's id
// type                 	integer	                                type of message
// activity?	            message activity object             	sent with Rich Presence-related chat embeds
// application?	            partial application object	            sent with Rich Presence-related chat embeds
// application_id?	        snowflake	                            if the message is a response to an Interaction, this is the id of the interaction's application
// message_reference?	    message reference object	            data showing the source of a crosspost, channel follow add, pin, or reply message
// flags?	                integer	                                message flags combined as a bitfield
// referenced_message?*****	?message object	                        the message associated with the message_reference
// interaction?	            message interaction object	            sent if the message is a response to an Interaction
// thread?	                channel object	                        the thread that was started from this message, includes thread member object
// components?	            Array of message components	            sent if the message contains components like buttons, action rows, or other interactive components
// sticker_items?	        array of message sticker item objects	sent if the message contains stickers

import { Snowflake } from '..'
import User from './User'

export default class Message {
    public readonly id: Snowflake
    public readonly channelID: Snowflake
    public readonly guildID?: Snowflake
    public readonly author: User
    public readonly member?: any
    public readonly content: string
    public readonly createdAt: Date
    public readonly editedAt?: Date
    public readonly tts: boolean
    public readonly mentionEveryone: boolean
    public readonly mentionsUsers: any[]
    public readonly mentionsRoles: any[]
    public readonly mentionsChannels: any[]
    public readonly attachments: any[]
    public readonly embeds: any[]
    public readonly reactions: any[]
    public readonly nonce: number | boolean
    public readonly pinned: boolean
    public readonly webhookID?: Snowflake
    public readonly type: 'DM' | 'GUILD_CHANNEL'
    public readonly activity?: any
    public readonly application?: any
    public readonly applicationID?: any
    public readonly messageReference?: any
    public readonly flags: any[]
    public readonly referencedMessage?: any
    public readonly interaction?: any
    public readonly thread?: any
    public readonly components: any[]
    public readonly stickerItems: any[]

    constructor(data: any) {
        this.id = data.id.toString()
        this.channelID = data.channel_id
        this.guildID = data.guild_id
        this.author = data.author
        this.member = data.author
        this.content = data.content
        this.createdAt = data.created_at
        this.editedAt = data.edited_at
        this.tts = data.tts
        this.mentionEveryone = data.mention_everyone
        this.mentionsUsers = data.mentions
        this.mentionsChannels = data.mentions_channels
        this.mentionsRoles = data.mentions_roles
        this.attachments = data.attachments
        this.embeds = data.embeds
        this.reactions = data.reactions || []
        this.nonce = data.nonce
        this.pinned = data.pinned
        this.webhookID = data.webhook_id
        this.type = data.type
        this.activity = data.activity
        this.application = data.application
        this.applicationID = data.application_id
        this.messageReference = data.message_reference
        this.flags = data.flags || []
        this.referencedMessage = data.referenced_message
        this.interaction = data.interaction
        this.thread = data.thread
        this.components = data.components || []
        this.stickerItems = data.sticker_items || []
    }
}
